# Generated by Django 4.1.2 on 2022-11-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim_meet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmeet',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swimmeet',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
