# Generated by Django 4.1.2 on 2022-10-30 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63fbc5cf-dc78-4bf7-bc72-2f55d5c498e2'), primary_key=True, serialize=False),
        ),
    ]
