# Generated by Django 4.1.2 on 2022-11-01 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_profile', '0006_alter_athleteprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e462c53-785d-4baa-ab88-161318bb144e'), primary_key=True, serialize=False),
        ),
    ]
