# Generated by Django 4.1.2 on 2022-10-30 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swim_meet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwimEvents',
            fields=[
                ('event_id', models.UUIDField(default=uuid.UUID('a195fae5-6e64-4668-a102-3d3c6307db1b'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('heat', models.IntegerField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('swim_meet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='swim_meet.swimmeet')),
            ],
        ),
    ]
