# Generated by Django 4.1.2 on 2022-10-30 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_profile', '0003_alter_athleteprofile_id'),
        ('swim_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwimHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_no', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='swimevents',
            old_name='heat',
            new_name='heats',
        ),
        migrations.RemoveField(
            model_name='swimevents',
            name='event_id',
        ),
        migrations.AddField(
            model_name='swimevents',
            name='event',
            field=models.UUIDField(default=uuid.UUID('2c8bd77f-8767-487c-9226-c7baae44fe53'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SwimmerEvent',
            fields=[
                ('comp', models.UUIDField(default=uuid.UUID('e1d41be4-87ff-4ecd-9801-c5d5a8cba4e7'), primary_key=True, serialize=False)),
                ('swim_time', models.DecimalField(decimal_places=4, max_digits=5)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete_profile.athleteprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swim_events.swimevents')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='swim_events.swimheat')),
            ],
        ),
        migrations.AddField(
            model_name='swimheat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='swim_events.swimevents'),
        ),
    ]
