# Generated by Django 4.1.2 on 2022-11-01 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swim_events', '0002_swimheat_rename_heat_swimevents_heats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimevents',
            name='event',
            field=models.UUIDField(default=uuid.UUID('ac04c168-dcb8-4187-b919-fa3fe7983e65'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='swimmerevent',
            name='comp',
            field=models.UUIDField(default=uuid.UUID('90db4097-907f-4362-9f92-29eae06743c7'), primary_key=True, serialize=False),
        ),
    ]
