# Generated by Django 4.1.2 on 2022-11-01 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swim_events', '0003_alter_swimevents_event_alter_swimmerevent_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimevents',
            name='event',
            field=models.UUIDField(default=uuid.UUID('df3bf21e-5116-481f-8cd1-a35ab71d63fe'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='swimmerevent',
            name='comp',
            field=models.UUIDField(default=uuid.UUID('f8916b41-d23b-4cca-83a8-f15157f90c17'), primary_key=True, serialize=False),
        ),
    ]
