# Generated by Django 4.1.2 on 2022-11-01 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swim_events', '0004_alter_swimevents_event_alter_swimmerevent_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimevents',
            name='event',
            field=models.UUIDField(default=uuid.UUID('e0fe32c0-b6db-43be-b934-84f4117d0471'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='swimmerevent',
            name='comp',
            field=models.UUIDField(default=uuid.UUID('12005438-ab00-4a9e-978c-eed3e506f4a8'), primary_key=True, serialize=False),
        ),
    ]
