# Generated by Django 4.1.2 on 2022-11-01 10:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swim_meet', '0002_alter_swimmeet_end_time_alter_swimmeet_start_time'),
        ('swim_events', '0005_alter_swimevents_event_alter_swimmerevent_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmerevent',
            name='comp',
            field=models.UUIDField(default=uuid.UUID('9b1bbbac-f087-463c-8111-4947fb9f697f'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SwimEvent',
            fields=[
                ('event', models.UUIDField(default=uuid.UUID('8135158c-8270-44ea-8502-4654745a5485'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('heats', models.IntegerField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('swim_meet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='swim_meet.swimmeet')),
            ],
        ),
        migrations.AlterField(
            model_name='swimheat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='swim_events.swimevent'),
        ),
        migrations.AlterField(
            model_name='swimmerevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swim_events.swimevent'),
        ),
        migrations.DeleteModel(
            name='SwimEvents',
        ),
    ]
