# Generated by Django 4.1.2 on 2022-10-16 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b7cefdff-1915-4baa-8f25-f5c028ce5fb9'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('squad', models.CharField(choices=[('RYA', 'Ryan A&B'), ('HGP', 'High Performance'), ('PER', 'Performance'), ('FRY', 'FRY A&B'), ('DEV', 'Development'), ('HEN', 'Hentschel'), ('OWM', 'Masters'), ('NOV', 'Novice')], default='NOV', max_length=3)),
                ('dob', models.DateField()),
            ],
        ),
    ]
